# Generated by Django 4.2.1 on 2023-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_rename_event_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
