# Generated by Django 4.2.1 on 2023-05-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_budget_event_guest_report_rsvp_event_report_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='agender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.agender'),
        ),
    ]
