# Generated by Django 4.2.1 on 2023-05-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_agender_event_agender_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_user_email', models.EmailField(max_length=255)),
                ('invitation_url', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.event')),
            ],
            options={
                'ordering': ('event',),
            },
        ),
    ]
