# Generated by Django 4.2.1 on 2023-05-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_name',
            new_name='username',
        ),
    ]
