# Generated by Django 4.2.1 on 2023-05-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rename_user_name_event_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agender',
            new_name='Agenda',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
