# Generated by Django 4.2.1 on 2023-05-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_rename_agender_agenda_remove_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='budget',
            new_name='budget_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='username',
            new_name='user_id',
        ),
    ]
